import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  list: [
    {
      list: {
        productName: "Cylinder",
        length: 2,
        breadth: 4,
        height: 5,
        volume: 2*4*5,
        image: "https://www.mathsisfun.com/geometry/images/cylinder-wood.jpg",
      },
    },
  ],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const appSlice = createSlice({
  name: "list",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addToList: (state, action) => {
         state.list.push(action.payload);
    },
    removeFromList: (state,action) => {
      state.list.splice(action.payload,1);
    },
    editListItem : (state,action) =>{
       const {index,list} = action.payload;
       const value = {list: list};
       state.list.splice(index,1,value)
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { addToList,editListItem } = appSlice.actions;

export const {removeFromList}  = appSlice.actions;

export const productList = (state) => state.app.list;

export default appSlice.reducer;
